# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
a = np.arange(10)
a=np.reshape(a,(2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
import numpy as np
x = np.array([[0,1,2,3,4],[5,6,7,8,9]])
y = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((x,y))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [5]:
import numpy as np
x = np.array([[0,1,2,3,4],[5,6,7,8,9]])
y = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [6]:
a = np.array([[0,1,2,3,4], [5,6,7,8,9]])
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [ ]:
np.flatten()

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [10]:
import numpy as np
#one dimensional
a = np.arange(15)
a=np.reshape(a,(5,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [12]:
import numpy as np
a=np.arange(15).reshape((5,3))
np.square(a)

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [18]:
import numpy as np
a = np.arange(30).reshape(5,6)
print(a)
np.mean(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [15]:
print ("\nMore precision with float32") 
print("std of a : ", np.std(a, dtype = np.float32)) 


More precision with float32
std of a :  8.655441


## Question:10

### Find the median of the previous array in Q8?

In [16]:
print("median of a : ", np.median(a))

median of a :  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [17]:
print("Transpose of a : ", np.transpose(a))

Transpose of a :  [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [21]:

n_array = np.array([[5, 2, 1, 4], 
                    [9, 4, 2, 5], 
                    [11, 5, 7, 3], 
                    [5, 6, 6, 7]]) 
  
# Displaying the Matrix 
print("Numpy Matrix is:") 
print(n_array) 

diag = np.diagonal(n_array) 
  
print("\nDiagonal elements are:") 
print(diag) 
  
print("\nSum of Diagonal elements is:") 
print(sum(diag)) 

Numpy Matrix is:
[[ 5  2  1  4]
 [ 9  4  2  5]
 [11  5  7  3]
 [ 5  6  6  7]]

Diagonal elements are:
[5 4 7 7]

Sum of Diagonal elements is:
23


## Question:13

### Find the determinant of the previous array in Q12?

In [22]:
print(np.linalg.det(n_array)) 

239.99999999999997


## Question:14

### Find the 5th and 95th percentile of an array?

In [24]:
print(np.percentile(n_array, 5))
np.percentile(n_array, 95)


1.75


9.5

## Question:15

### How to find if a given array has any null values?

In [ ]:
Checking for NaN elements in a NumPy array returns True if the array contains any NaN elements and False otherwise.

USE numpy.sum() AND numpy.isnan() TO CHECK FOR NAN ELEMENTS IN AN ARRAY
Call numpy.sum(a) to get the sum of the array a. The result will be NaN if and only if a has one or more NaN values. Call numpy.isnan(x) to check if the previous result x is NaN.